FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN apt-get update && apt-get install -y ocrmypdf tesseract-ocr ghostscript && \
    pip install --no-cache-dir -r requirements.txt

COPY app/ ./app
WORKDIR /app/app

CMD ["celery", "-A", "tasks", "worker", "--loglevel=info"]