FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN apt-get update && apt-get install -y libjpeg-dev zlib1g-dev && \
    pip install --no-cache-dir -r requirements.txt

COPY app/ ./app
WORKDIR /app/app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]