version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./results:/results
    depends_on:
      - redis
      - worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./app:/app
      - ./results:/results
    depends_on:
      - redis

  redis:
    image: redis:7